- README.md
- database_guide.md
- mysite/settings.py
- requirement.txt
- sample.env
Change database part in mysite/settings.py
Create sample .env file
Add database installation guide
> Config setting to use MySQL as a main DBMS

- README.md
Status badges added to README.md
> Add status badges into README.md

- .flake8
- activities/templates/base.html
- activities/tests/shortcuts.py
- activities/tests/test_detail.py
- activities/tests/test_index.py
- activities/tests/test_join.py
- activities/urls.py
- activities/views.py
- frontend/.jshintignore
- frontend/.jshintrc
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.vue
- frontend/src/api.js
- frontend/src/main.js
- frontend/src/router/index.js
- frontend/src/styles/ActivityDetail.css
- frontend/src/styles/ActivityIndex.css
- frontend/src/utils/csrf.js
- frontend/src/views/ActivityDetail.vue
- frontend/src/views/ActivityIndex.vue
- frontend/vue.config.js
- mypy.ini
- mysite/settings.py
- mysite/urls.py
Vue and Django connects to each other
- Django works as backend behind the scene
- Vue works as frontend for user interaction
> Connect vue to backend

- database_guide.md
- mypy.ini
- mysite/__init__.py
- mysite/settings.py
- requirements.txt
Change database interface to pymysql instead of mysqlclient. Since it cause lot a problem.
> Config database

- database_guide.md
- mypy.ini
- mysite/__init__.py
- mysite/settings.py
- requirements.txt
Reverts OmegaOoh/ku-tangtee#30 doens't pass test after merge for some reason
> Revert "Config database"

- .flake8
- activities/tests/test_create_activity.py
- activities/urls.py
- activities/views.py
Note that
- This is bare-bones create activity function without checking that activity name and detail are appropriate or not .
- I assume that date will sent as a string with format `%Y-%m-%dT%H:%M` which is default format that get from HTML input type datetime-local. if the format are differ I can change It later.
> Handle create activity

- frontend/package-lock.json
- frontend/package.json
- frontend/postcss.config.js
- frontend/src/styles/styles.css
- frontend/tailwind.config.js
It is a UI library for vue that might help us.
> Installed daisyui

- codecov.yml
Set target coverage to 80%
and make the codecov wait for ci finished
> Create  codecov.yml

- codecov.yml
Set patch target to 80% instead of greater than previous
> Add patch target for coverage

- activities/tests/shortcuts.py
- activities/views.py
- frontend/src/App.vue
- frontend/src/styles/ActivityDetail.css
- frontend/src/styles/ActivityIndex.css
- frontend/src/styles/WhiteText.css
- frontend/src/views/ActivityCreate.vue
- frontend/src/views/ActivityDetail.vue
- frontend/src/views/ActivityEdit.vue
- frontend/src/views/ActivityIndex.vue
- Pages now synchronized with themes (dark and light)
- Activity Index page now has 2 activities per row
- Activity Detail page now synchronized with the theme
- Every page contains a header row shows user that login or login button
- Fixed issues of light theme in ActivityEdit and ActivityCreate pages
> Create base template and Renovate some existed page appearances

- frontend/src/App.vue
Before: If user logged in and refresh the page it will show `Welcome, ` without username.
Simple fix is to called `getUserData()`, but to ensure that token is valid, POST request to `.../rest-auth/token/verify` and catch the error if there is error, then token is not valid and user need to login again, otherwise user is logged in and `getUserData is called`
> Verify and get user data after refresh page

- frontend/src/views/ActivityIndex.vue
Every 5 seconds frontend will fetch the activities index from API.
> Periodically refresh activity index.

- frontend/sample.env
- frontend/src/api.js
Vue --API--> Django
We externalize Vue_app_base_url (Django base url to use to connect)
> Externalize base url

- activities/consumers.py
- activities/routing.py
- activities/views.py
- frontend/src/views/ActivityIndex.vue
- mysite/asgi.py
The previous implementation of periodically fetching the data could be a problem if there is high traffic on the website. Change to use the WebSocket to monitor the change and add the button to fetch the data if there is any new activity.
> Add button for user to reload the page if there is new activity

- frontend/src/App.vue
- frontend/src/api.js
- frontend/src/component/AlertToast.vue
- frontend/src/functions/AlertManager.js
- frontend/src/functions/Authentications.js
- frontend/src/functions/HttpRequest.js
- frontend/src/main.js
- frontend/src/views/ActivityCreate.vue
- frontend/src/views/ActivityDetail.vue
- frontend/src/views/ActivityEdit.vue
- frontend/src/views/ActivityIndex.vue
- Remove duplicates codes
- Create Custom Alert
> Implement Custom Alert for frontend

- frontend/src/component/ImageCarousel.vue
- frontend/src/component/ImageGrid.vue
- frontend/src/component/ImagePreview.vue
- frontend/src/functions/Utils..js
- frontend/src/views/ActivityChat.vue
- frontend/src/views/ActivityCreate.vue
This PR is to merge into `images-backend` branch and will close #137 #131 
- Add the image component
- Chat and Activity Create to have the File upload restricted to only images
- Can Select and See the image on Chat and Activity creation page
> Frontend image upload and show

- .flake8
- frontend/src/views/ActivityIndex.vue
- In ActivityIndex page, there are dropdown for filtering days and datepicker to filter the date range.
- You can use multiple filter options with search bar at the same time.
- #173 
- User can filter activities using multiple options at the same time. (Date range, Day and Keyword)
> Search bar and filter by day and date range

- activities/models.py
- activities/serializer/model_serializers.py
- activities/tests/test_activities.py
- activities/views/util.py
- google_credentials_guide.md
- Include `get_recent_activity` in code coverage #140 
- Remove duplicate method in Attend model class #144 
- Improve serializer class doctoring #147 
- Clarify class name to be more descriptive #148 
- Add missing step in google credentials guide
- Application running well after fix
> Code review fix

- frontend/package-lock.json
- frontend/package.json
- frontend/src/component/CheckInCodeModal.vue
- frontend/src/component/CheckInModal.vue
- frontend/src/component/CheckInQRCodeModal.vue
- frontend/src/views/ActivityDetail.vue
- frontend/src/views/ProfileCreate.vue
- frontend/src/views/ProfilePage.vue
Implement check-in via QR code which works by generate QR code of the activity with query params `code=<check-in code>`
- Host can shows QR code that's contains the check-in code of he activity.
- 
QR Code won't be updated when code is set/change after the first fetch. This will be fixed by using API to get check in code
> QR Code for Check-in

- activities/models.py
- activities/tests/test_activities.py
- activities/views/util.py
- frontend/src/views/ProfilePage.vue
- profiles/models.py
- profiles/serializer/model_serializers.py
- Show the separated data between hosted activities and joined activities using selectable tabs
* #211 
* #212
> Seperate hosted and joined activity

- INSTALLATION.md
- README.md
- google_credentials_guide.md
- shorten the readme to be simpler and easier to read,
- Installation guide is on the separated file.
> README revision

- INSTALLATION.md
- LICENSE
- frontend/README.md
- Update the installation guide to be more concise, user-friendly, and cleaner in format. #238
- Add MIT License. #244 
You can inform me or directly change the instructions on this branch as you wish
> Update INSTALLATION.md and Add MIT License

- .github/workflows/coverage.yml
- backend/requirements-dev.txt
- Separate requirements for development and productions
> Separate requirements for development and productions

- backend/mysite/__init__.py
- backend/mysite/settings.py
- move pymysql imports to __init__.py of mysite module
> move pymysql imports to __init__.py of mysite module

- frontend/src/views/ActivityChat.vue
- Add extra / to websocket url
> Fix websocket

- frontend/src/component/NavBar.vue
- frontend/src/views/ActivityDetail.vue
- frontend/src/views/ProfilePage.vue
* Improve grammar in Activity Detail page, Profile page and Navbar
* Improve Navbar to display only 1 line of activity name
* Closes #257 
* Closes #258
> Grammartical improvements and Navbar stylish improvement

- backend/activities/views/activity_checkin.py
- backend/activities/views/activity_list.py
- backend/activities/views/activity_paticipant.py
- backend/chat/permissions.py
- backend/chat/routing.py
- backend/chat/tests/test_chat_view.py
- backend/chat/views.py
- frontend/src/functions/Authentications.js
- frontend/src/functions/HttpRequest.js
- frontend/src/views/ActivityChat.vue
- frontend/src/views/ActivityCreate.vue
- frontend/src/views/ActivityIndex.vue
- frontend/src/views/ProfileCreate.vue
- Fix the frontend issue related to #265 
- Some frontend behaviors to prevent #264 by spamming the button on the UI
- User can Spy on any chat #270 
- Undefined goNext on Profile Creation Page #269 
- Show proper error message and trimmed the text on input field (this related to #268)
Everything works the same and features now have start_date and end_date with their query params
Button disable while processing create request (Create activity/profile).
on POST, PUT, DELETE now showing the message from backend
> Bug fixes: Fix bugs on frontend and page permissions

- frontend/src/component/CheckInCodeModal.vue
- frontend/src/component/CheckInModal.vue
- frontend/src/component/EditModal.vue
- frontend/src/component/EditPermModal.vue
- frontend/src/functions/HttpRequest.js
- frontend/src/views/ActivityCreate.vue
- frontend/src/views/ActivityDetail.vue
- frontend/src/views/ProfileCreate.vue
- frontend/src/views/ProfilePage.vue
- Fix bug where unexpected error shown along with normal error message
Everything should works the same and no more double alert message
> HOT FIX: Fix bug where unexpected error shown along with normal error message

- INSTALLATION.md
- README.md
- #261 :
- Change the directory in the instructions after the repository structure changes.
- Add activate and deactivate Virtual Environment steps.
- Minor instructions corrections.
> Revise the installation and running the application instructions
